### ISSUE TITLE
The user set the permission to Editor, however this field cannot be updated with the requests.patch method

### ISSUE THREAD

**Issue by ZenonH** [gtalarico/pyairtable#228] opened 2023-02-16 17:20 UTC
b'{"error":{"type":"INVALID_PERMISSIONS","message":"You are not permitted to perform this operation because the field \\"Access Date 1\\" (fld0EAbaCB1WbXghF) has been configured to limit who can perform this operation"}}'

The owner of the database has set the permission level to Editor, but to no avail.

**Comment by marks** [comment] 2023-02-26 21:15
Hi @ZenonH - I don't think this error is actually related to this library. There is actually a feature in Airtable where the base creator can limit a user with Editor access further: https://support.airtable.com/docs/en/using-field-and-table-editing-permissions

**Comment by mesozoic** [comment] 2023-05-05 07:59
I concur with @marks, this is not a bug with the Python library. Closing the issue.

**Closed by mesozoic** 2023-05-05 07:59 UTC
