### ISSUE TITLE
Adding field id support to ORM

### ISSUE THREAD

**Issue by Bryntet** [gtalarico/pyairtable#232] opened 2023-03-05 16:52 UTC
I would appreciate that SO much!!! :)

**Comment by mesozoic** [comment] 2023-04-30 22:58
Hi, can you clarify what you'd like to be able to do with the ORM that you're not able to do today? Sample code might help!

**Comment by enxyz** [comment] 2023-06-29 16:13
I came here with a similar request, expect this issue is essentially [issue 187](https://github.com/gtalarico/pyairtable/issues/187), which seems to be to be coded and ready for release in the [upcoming 2.0](https://github.com/gtalarico/pyairtable/issues/249)

**Comment by mesozoic** [comment] 2023-07-25 06:03
Going to close this as a duplicate of #187

**Closed by mesozoic** 2023-07-25 06:03 UTC
