### ISSUE TITLE
Issue with creating multipleRecordLinks '0.options.isReversed is missing'

### ISSUE THREAD

**Issue by Ledoux** [gtalarico/pyairtable#368] opened 2024-04-20 13:16 UTC
Hi I want to create a link content.account from a 'contents' table towards the associated account (via the content.accountId field).

When I try to create the link and the reverse link :

```python
linked_field = accounts_table.create_field(
    'contents', 
    'multipleRecordLinks', 
    options={
        'linkedTableId': contents_table.id
    }
)

 contents_table.create_field(
      'account', 
      'multipleRecordLinks', 
      options={
          'inverseLinkFieldId': linked_field.id,
          'linkedTableId': accounts_table.id,
          'prefersSingleRecordLink': True
     }
)
 ```

I cannot, I have such issues :
        
```
requests.exceptions.HTTPError: ('422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/meta/bases/appYDDFYw4ZmrGAa0/tables/tbl3s3YftIiu3G8X5/fields', "{'type': 'INVALID_FIELD_TYPE_OPTIONS_FOR_CREATE', 'message': 'Invalid options for contents.account: Failed schema validation: account.0.options.isReversed is missing, prefersSingleRecordLink is not included in the account.1.options schema'}")
```

I tried a bit to add all the permutation possibles with isReversed, and inverseLinkFieldId but I m stuck,it would be cooll to have a better understanding of this api please, thanks a lot:)

Best,

**Comment by BAPCon** [comment] 2024-04-22 09:45
https://community.airtable.com/t5/development-apis/creating-a-table-with-multiplerecordlinks-field-with-rest-api/m-p/157602#M12761

I can't find any working examples of this functionality even from the REST API, in the mean time I would suggest using lookup tables with one field being the primary field.

**Comment by mesozoic** [comment] 2024-04-22 21:43
Reading the [API documentation for multipleRecordLinks](https://airtable.com/developers/web/api/field-model#foreignkey), it looks like the only options they support for creating or updating fields are `linkedTableId` and `viewIdForRecordSelection`. The `inverseLinkFieldId` and `prefersSingleRecordLink` properties are only available when reading the field metadata.

My understanding of how these fields work is that creating a link field from table1→table2 should _automatically_ create the reciprocal field on table2, which you'd be able to identify by looking at the `inverseLinkFieldId` property. For example:

```python
>>> created_field = table1.create_field('link', 'multipleRecordLinks', options={'linkedTableId': table2.schema().id})
>>> created_field
MultipleRecordLinksFieldSchema(type='multipleRecordLinks', options=MultipleRecordLinksFieldOptions(is_reversed=False, linked_table_id='tbl...', prefers_single_record_link=False, inverse_link_field_id='fldVIhHyCq5yUbWDb', view_id_for_record_selection=None), id='fld9GFYJfZo8hk1UG', name='link', description=None)
>>> inverse = next(
...     field for field in table2.schema(force=True)
...     if field.type == "multipleRecordLinks"
...     and field.options.inverse_link_field_id = created_field.id
... )
>>> inverse
MultipleRecordLinksFieldSchema(type='multipleRecordLinks', options=MultipleRecordLinksFieldOptions(is_reversed=False, linked_table_id='tbl...', prefers_single_record_link=False, inverse_link_field_id='fld9GFYJfZo8hk1UG', view_id_for_record_selection=None), id='fldVIhHyCq5yUbWDb', name='One', description=None)
```

I'm going to close this issue since it's not a bug with the pyairtable library. I suggest asking on the [Airtable Community Forums](https://community.airtable.com/) if you have follow-up questions or feature requests.

**Closed by mesozoic** 2024-04-22 21:43 UTC
