### ISSUE TITLE
Import conflict with pydantic 2.10.0

### ISSUE THREAD

**Issue by twhalm** [gtalarico/pyairtable#411] opened 2024-11-21 16:34 UTC
With pydantic v2.10.0, importing pyairtable causes the following error:

```
Exception has occurred: AttributeError
partially initialized module 'pyairtable' has no attribute 'api' (most likely due to a circular import)
  File "file.py", line 2, in <module>
    from pyairtable import Api
AttributeError: partially initialized module 'pyairtable' has no attribute 'api' (most likely due to a circular import)
```
This error does not occur with earlier versions of pydantic.

**Comment by shaunagm** [comment] 2024-11-21 16:35
I'm getting this error and we don't have pydantic installed at all.

**Comment by JasonCrowe** [comment] 2024-11-21 17:49
I backed off to 2.9 and it's working.

**Comment by Eagles0607** [comment] 2024-11-22 19:05
Backing off to 2.9 worked for me as well.

**Comment by sungmincs** [comment] 2024-11-23 14:18
Pydantic 2.10.1 still doesn't fix this issue.

**Comment by Viicos** [comment] 2024-11-24 17:55
This should be fixed in 2.10.2, coming next week. The reason you are getting this issue is because the following `_api` private field annotation:

https://github.com/gtalarico/pyairtable/blob/34eb78e5b7b9a348dcf82dd23e53abc611b67e31/pyairtable/models/_base.py#L124-L135

failed to be evaluated in Pydantic <= 2.9. In 2.10, we refactored our forward annotation evaluation logic to be more correct, meaning it does evaluate the forward annotation as expected. However, this leads to a circular import because the `pyairtable.api.api` module is already in the process of being imported when this forward annotation is evaluated.

2.10.2 will include a fix to _not_ evaluate forward annotations for private fields, because we don't make use of the annotation any way.

**Comment by mesozoic** [comment] 2024-11-24 19:56
Thanks @Viicos for keeping us updated, and for working toward a patch to fix the issue. 🙌  

In the meantime I've opened #412 in case anyone out there has ideas for how to remove the circular dependencies caused by type annotations in this library.

**Comment by Viicos** [comment] 2024-11-24 20:19
> In the meantime I've opened #412 in case anyone out there has ideas for how to remove the circular dependencies caused by type annotations in this library.

Note that as long as these circular issues happens in private attributes, it shouldn't be an issue anymore in the next patch release. But yeah, if they are used for "normal" Pydantic fields, this is going to be an issue.

**Comment by coronarita1991** [comment] 2024-11-25 02:50
I got a same error as above while importing pyairtable, and solved with downgrading pydantic with 2.9.2. After solving issue I could reach this post. Anyway, thanks.

**Comment by LouisMonierSpark** [comment] 2024-11-25 13:56
Super painful issue. This should be prioritized asap.

**Comment by Viicos** [comment] 2024-11-26 13:19
2.10.2 is now released, and fixes the issue.

**Comment by mesozoic** [comment] 2024-11-28 04:29
Thank you for the fix, @Viicos! I'll resolve this issue now.

> Note that as long as these circular issues happens in private attributes, it shouldn't be an issue anymore in the next patch release. But yeah, if they are used for "normal" Pydantic fields, this is going to be an issue.

Heard! I don't foresee us adding any more things like this, but it'll still be an interesting mental exercise to rethink the dependency graph within the library. Thanks again for your help.

**Closed by mesozoic** 2024-11-28 04:29 UTC
